[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
burve_solana_contract = "3bZ4oQHBhP95DVdBteTG13meav1qEnKnUzxb5SjmSpQH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/han/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
